Jaf.loadDictionnaire('FR',{
    DIC_A					   : 'à',
	DIC_A_CONFIRMER            : 'à confirmer',
	DIC_A_FERMER	           : 'à fermer',
	DIC_ARRIVEE		           : 'Arrivée',
    DIC_ATTESTATION_VTC        : 'Attestation',
	DIC_CLIENT                 : 'Client',
	DIC_CLIENTS_AUTRES         : 'Clients, Contacts, Passagers',
	DIC_COMMENTAIRE		       : 'Commentaire',
	DIC_COMMENTAIRE_MISSION    : 'Commentaire sur la mission',
    DIC_CONFIRMER              : 'Confirmer',
    DIC_CONTACT                : 'contact',
	DIC_CONNEXION              : 'Connexion',
    DIC_DATE_A_PARTIR_DU       : 'A partir du ',
    DIC_DATE_AU                : ' au ',
    DIC_DATE_DU                : 'Du ',
	DIC_DATE_DEBUT             : 'Date de début',
	DIC_DATE_FIN               : 'Date fin',
	DIC_DE					   : 'de',
	DIC_DEBOURS				   : 'Débours',
	DIC_DECONNEXION			   : 'Déconnexion',
    DIC_DEMARRER               : 'DEMARRER',
    DIC_DEPART                 : 'DEPART',
	DIC_départ                 : 'Départ',
    DIC_DEPOSE_CLIENT          : 'DEPOSE CLIENT',
	DIC_DETAIL_MISSION         : 'Détail mission',
    DIC_EN_PLACE               : 'EN PLACE',
	DIC_ENREGISTRER            : 'Enregistrer',
	DIC_EXEMPLE_HEURE          : 'exemple : 1520 ou 15:20 pour dire 15h20',
    DIC_FERMER                 : 'Fermer',
    DIC_FRAIS                  : 'Frais',
	DIC_GOOGLE_AGENDA		   : 'LIMO AGENDA',
	DIC_GOOGLE_AGENDA_TITRE	   : 'Google Agenda',
	DIC_GOOGLE_AGENDA_CREER	   : 'Pensez à cocher le nouvel agenda crée dans "Mes agendas".',
	DIC_GOOGLE_AGENDA_PARAMET  : 'Renseignez vos identifiants Google pour paramétrer un nouveau compte. Ces informations sont confidentielles et ne seront pas conservées par Limo.',
	DIC_GOOGLE_AGENDA_VERIFIER : 'Vous devez vérifier depuis votre compte,<br>onglet "SECURITE" puis "ACTIVITE RECENTE"<br>si google ne vous demande pas d\'accepter cette création.".',
	DIC_GOOGLE_AGENDA_VOTRE	   : 'Votre Google Agenda',
	DIC_H_DEBUT_MISSION        : 'Heure début mission',
	DIC_H_FIN_MISSION          : 'Heure fin de mission',
	DIC_HEURE	               : 'Heure',
    DIC_HEURE_FIN              : 'Heure<br>fin',
    DIC_ITINERAIRE             : 'Itinéraire',
    DIC_KILOMETRAGE_COMPTEUR   : 'Kilométrage au compteur ?',
	DIC_KM_DEBUT_MISSION	   : 'Km début de mission',
	DIC_KM_FIN_MISSION	   	   : 'Km fin de mission',
	DIC_KM		               : 'Km',
    DIC_KM_ET_HEURE            : 'Heures et Km',
	DIC_LANCER_DEBUG		   : 'Lancer le debuggage',
	DIC_LANGAGE				   : 'Langage',
	DIC_LE					   : 'le',
	DIC_LIMO_DRIVER			   : 'LIMO DRIVER',
	DIC_LOG					   : 'Log',
	DIC_LOGIN				   : 'Login',
	DIC_MISE_A_JOUR			   : 'Mise à jour',	
    DIC_MISSION_A_CONFIRMER    : 'Missions à confirmer',
    DIC_MISSION_CONFIRMER      : 'Confirmé',
    DIC_MISSION_EN_COURS       : 'En cours',
    DIC_MISSION_A_FERMER       : 'Missions à fermer',
    DIC_MISSION_FERMER         : 'Fermé',
    DIC_MISSION_MODIFIER       : 'Missions modifiées',
    DIC_MISSION_PLURIEL        : 'missions',
    DIC_MISSION_SAUVER         : 'Sauvé',
    DIC_MISSION_SINGULIER      : ' mission',
	DIC_MODE_DEPANNAGE	       : 'Mode dépannage',
    DIC_MODE_REGLEMENT	       : 'Mode de règlement',
	DIC_MODIFIEES		       : 'modifiée(s)',
	DIC_MONTANT_ENCAISSE       : 'Montant encaissé',
	DIC_MOT_DE_PASSE	       : 'Mot de passe',
	DIC_NOUVELLE_VERSION       : 'Une nouvelle version de limodriver est disponible, voulez vous la télécharger ?',
    DIC_NOTE_CHAUFFEUR         : 'Note au chauffeur',
    DIC_NO_SHOW                : 'NO SHOW',
    DIC_NO_SHOW_RAISON         : 'Quelle raison pour le NO SHOW',
    DIC_NO_SHOW_PAS_CLIENT     : 'Le client n\'était pas au rendez-vous',
	DIC_N_EXPLOITANT           : 'N° exploitant',
	DIC_N_DOSSIER	           : 'n°Dossier',
    DIC_PANNEAU                : 'Panneau',
	DIC_PARKING                : 'Parking',
    DIC_PASSAGERS              : 'Passagers',
    DIC_PASSAGER_DOIT_DESCEN1  : 'doit descendre à la prochaine étape',
    DIC_PASSAGER_DOIT_DESCEN2  : 'doit descendre',
    DIC_PASSAGER_PROCHAINE     : 'doit monter à la prochaine étape',
    DIC_PASSAGER_PRESENT       : 'PRESENT',
    DIC_PAS_A_JOUR             : 'Votre LimoDriver n\'est peut être pas à jour. Veuillez trouver une connexion internet pour vous synchroniser.',
    DIC_PAS_DE_LIEU_ICI        : 'Problème pas de lieu ici',
	DIC_PEAGE			       : 'Péage',
    DIC_PREVUE                 : 'h prévue(s)',
    DIC_PROCHAINE_MISSION      : 'Prochaine mission',
    DIC_PROGRAMME              : 'Programme',
    DIC_RAZ		               : 'RAZ',	
    DIC_RECHARGEMENT_COMPLET   : 'Re-chargement complet de l\'application en cours.<br><br>Suppression de',
    DIC_RECHARGEMENT_DEMAN     : 'Votre LimoDriver doit être totalement rechargé suite à un changement de version du logiciel. Si vous cliquez sur OK alors toutes vos données seront supprimées et remplacées par celle en ligne.',
    DIC_RECHARGEMENT_ETAPE1    : 'Etape 1 - Rechargement simple',
    DIC_RECHARGEMENT_ETAPE2    : 'Etape 2 - Rechargement complet',
	DIC_RECHARGEMENT_COMPLET   : 'Rechargement complet',
	DIC_RECHERCHE              : 'Recherche',
	DIC_RECHERCHER             : 'RECHERCHER',
    DIC_REF_CLIENT             : 'Ref client',
	DIC_REPAS	               : 'Repas',
	DIC_RESA_ENREGISTREE       : 'Réservation enregistrée',
	DIC_TEXTE_REGLEMENTATION   : 'Réglementation : Conformement aux articles L.231-1, L.231-2, L.231-3 du code du tourisme, voici les informations à présenter lors d\'un contrôle.',
    DIC_SI_BLOQUE_SUIVANT      : 'Si vous restez bloqué, suivez les étapes suivantes',
	DIC_TELECHARGER            : 'Télécharger',
	DIC_UTILISATEUR	           : 'Utilisateur',
    DIC_VEHICULE               : 'Véhicule',
    DIC_VEUI_PAT_CHAR          : 'Veuillez patientez pendant le chargement des données',
    DIC_VOIR_EN_GRAND          : 'Voir en grand',
    DIC_TELEPHONE              : 'Téléphone',
    DIC_TERMINER               : 'TERMINER',
    DIC_TYPE_SERVICE           : 'Service',
	
     
	XX : ''
});

Jaf.loadDictionnaire('EN',{
    DIC_A					   : 'to',
	DIC_A_CONFIRMER            : 'to confirm',
	DIC_A_FERMER	           : 'to close',
	DIC_ARRIVEE		           : 'Arrival',
    DIC_ATTESTATION_VTC        : 'Transport certificate',
	DIC_CLIENT                 : 'Customer',
	DIC_CLIENTS_AUTRES         : 'Customers, Passengers',
	DIC_COMMENTAIRE		       : 'Comment',
	DIC_COMMENTAIRE_MISSION    : 'Comment on the ride',
    DIC_CONFIRMER              : 'Confirm',
    DIC_CONTACT                : 'contact',
	DIC_CONNEXION              : 'Connection',
    DIC_DATE_A_PARTIR_DU       : 'From the ',
    DIC_DATE_AU                : ' to the ',
    DIC_DATE_DU                : 'From the ',
	DIC_DATE_DEBUT             : 'Start date',
	DIC_DATE_FIN               : 'End date',
	DIC_DE					   : 'from',
	DIC_DEBOURS				   : 'Expenses',
	DIC_DECONNEXION			   : 'Logout',
    DIC_DEMARRER               : 'START',
    DIC_DEPART                 : 'DEPARTURE',
	DIC_départ                 : 'Departure',
    DIC_DEPOSE_CLIENT          : 'DROP OFF',
	DIC_DETAIL_MISSION         : 'Ride details',
    DIC_EN_PLACE               : 'READY',
	DIC_ENREGISTRER            : 'Save',
	DIC_EXEMPLE_HEURE          : 'for example : 0320PM or 03:20PM to save 03:20 PM',
    DIC_FERMER                 : 'Close',
    DIC_FRAIS                  : 'Expenses',
	DIC_GOOGLE_AGENDA		   : 'LIMO CALENDAR',
	DIC_GOOGLE_AGENDA_TITRE	   : 'Google Calendar',
	DIC_GOOGLE_AGENDA_CREER	   : 'Remember to check the new agenda created in "My Calendars".',
	DIC_GOOGLE_AGENDA_PARAMET  : 'Write here your Google password and Google login to set a new account. Those informations are confidential and will not be recorded by Limo.',
	DIC_GOOGLE_AGENDA_VERIFIER : 'You must check from your Google account,<br>in "RECENT ACIVITY"<br>if you have to accept the new agenda created.".',
	DIC_GOOGLE_AGENDA_VOTRE	   : 'Your Google Calendar',
	DIC_H_DEBUT_MISSION        : 'Start time mission',
	DIC_H_FIN_MISSION          : 'End time mission',
	DIC_HEURE	               : 'Time',
    DIC_HEURE_FIN              : 'End<br>time',
    DIC_ITINERAIRE             : 'Route',
    DIC_KILOMETRAGE_COMPTEUR   : 'Mileage counter ?',
	DIC_KM_DEBUT_MISSION	   : 'Mileage mission start',
	DIC_KM_FIN_MISSION	   	   : 'Mileage mission end',
	DIC_KM		               : 'Mileage',
    DIC_KM_ET_HEURE            : 'Time and mileage',
	DIC_LANCER_DEBUG		   : 'Start debugging',
	DIC_LANGAGE				   : 'Language',
	DIC_LIMO_DRIVER			   : 'LIMO DRIVER',
	DIC_LOG					   : 'Log',
	DIC_LOGIN				   : 'Login',
	DIC_MISE_A_JOUR			   : 'Update',	
    DIC_MISSION_A_CONFIRMER    : 'Rides to be confirmed',
    DIC_MISSION_CONFIRMER      : 'Confirmed',
    DIC_MISSION_EN_COURS       : 'In progress',
    DIC_MISSION_A_FERMER       : 'Rides to be closed',
    DIC_MISSION_FERMER         : 'Closed',
    DIC_MISSION_MODIFIER       : 'Updated Missions',
    DIC_MISSION_PLURIEL        : 'missions',
    DIC_MISSION_SAUVER         : 'Saved',
    DIC_MISSION_SINGULIER      : ' mission',
	DIC_MODE_DEPANNAGE	       : 'Troubleshooting mode',
    DIC_MODE_REGLEMENT	       : 'Payment method',
	DIC_MODIFIEES		       : 'saved',
	DIC_MONTANT_ENCAISSE       : 'Amount received',
	DIC_MOT_DE_PASSE	       : 'Password',
	DIC_NOUVELLE_VERSION       : 'A new version of Limo Driver is available, do you want to download it ?',
    DIC_NOTE_CHAUFFEUR         : 'Notes to the driver',
    DIC_NO_SHOW                : 'NO SHOW',
    DIC_NO_SHOW_RAISON         : 'What is the reason for NO SHOW ?',
    DIC_NO_SHOW_PAS_CLIENT     : 'The customer missed the appointment',
	DIC_N_EXPLOITANT           : 'Company number',
	DIC_N_DOSSIER	           : 'Folder number',
    DIC_PANNEAU                : 'Welcome sign',
	DIC_PARKING                : 'Parking',
    DIC_PASSAGERS              : 'Passengers',
    DIC_PASSAGER_DOIT_DESCEN1  : 'gets off at the next step',
    DIC_PASSAGER_DOIT_DESCEN2  : 'must get off',
    DIC_PASSAGER_PROCHAINE     : 'pick up to the next step',
    DIC_PASSAGER_PRESENT       : 'PICK UP',
    DIC_PAS_A_JOUR             : 'Your Limo Driver is probably not updated. Please find an internet connection to synchronize your datas.',
    DIC_PAS_DE_LIEU_ICI        : 'Sorry : no place found',
	DIC_PEAGE			       : 'Toll',
    DIC_PREVUE                 : 'Expected time',
    DIC_PROCHAINE_MISSION      : 'Next ride',
    DIC_PROGRAMME              : 'Schedule',
    DIC_RAZ		               : 'Reset',	
    DIC_RECHARGEMENT_COMPLET   : 'Complet update of Limo Driver in progress.<br><br>Removal of',
    DIC_RECHARGEMENT_DEMAN     : 'Download the new Limo Driver to update the last version of the software. If you confirm all your local data will be deleted to be replaced by the latest ones.',
    DIC_RECHARGEMENT_ETAPE1    : 'Step 1 - Simple update',
    DIC_RECHARGEMENT_ETAPE2    : 'Step 2 - Complete update',
	DIC_RECHARGEMENT_COMPLET   : 'Complete update',
	DIC_RECHERCHE              : 'Search',
	DIC_RECHERCHER             : 'SEARCH',
    DIC_REF_CLIENT             : 'Customer id',
	DIC_REPAS	               : 'Meal',
	DIC_RESA_ENREGISTREE       : 'Recorded reservation',
	DIC_TEXTE_REGLEMENTATION   : 'Regulation : here are the information to be presented at a police check.',
    DIC_SI_BLOQUE_SUIVANT      : 'if you are blocked, follow the next steps',
	DIC_TELECHARGER            : 'Download',
	DIC_UTILISATEUR	           : 'User',
    DIC_VEHICULE               : 'Vehicule',
    DIC_VEUI_PAT_CHAR          : 'Please be patient during Limo download all the necessary datas',
    DIC_VOIR_EN_GRAND          : 'Open the Welcome sign',
    DIC_TELEPHONE              : 'Phone',
    DIC_TERMINER               : 'FINISH',
	DIC_LE                     : 'the',
    DIC_DE                     : 'from',
    DIC_TYPE_SERVICE           : 'Service',
     
	XX : ''
    
});